rango/urls.py
from django.conf.urls import url

from rango import views

app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(
        r'^category/(?P<category_name_slug>[\w\-]+)/$',
        views.show_category, name='show_category'),
    url(
        r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$',
        views.add_page, name='add_page'),
    # url(r'^register/$', views.register, name='register'),
    # url(r'^login/$', views.user_login, name='login'),
    # url(r'^logout/$', views.user_logout, name='logout')
    url(r'^restricted/', views.restricted, name='restricted'),
    
]

tango_with_django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from rango import views

from registration.backends.simple.views import RegistrationView

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/rango/'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^rango/', include('rango.urls')),
    url(r'^admin/', admin.site.urls),
     url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Category(models.Model):
    CHAR_MAX_LENGTH = 128

    name = models.CharField(max_length=CHAR_MAX_LENGTH, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    CHAR_MAX_LENGTH = 128

    category = models.ForeignKey(Category)
    title = models.CharField(max_length=CHAR_MAX_LENGTH)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)

    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Category, Page, UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.CHAR_MAX_LENGTH, help_text="Please enter the category Name")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.CHAR_MAX_LENGTH, help_text="Please enter the title of the page")
    url = forms.URLField(max_length=Page.CHAR_MAX_LENGTH, help_text="Please enter the url of the page")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category', )

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

            return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from datetime import datetime

from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visits', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits


def index(request):
    categories = Category.objects.order_by('-likes')[:5]
    pages = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': categories, 'pages': pages}
    return render(request, 'rango/index.html', context_dict)


def about(request):
    visitor_cookie_handler(request)
    context_dict = {"my_name": "Heriyanto"}
    context_dict['visits'] = request.session['visits']
    return render(request, 'rango/about.html', context_dict)


def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None
    
    return render(request, 'rango/category.html', context_dict)

@login_required
def add_category(request):

    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)

    context_dict = {'form':form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['pictures']

            profile.save()

            registred = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm() 
    
    return render(
        request,
        'rango/register.html',
        {
            'user_form': user_form,
            'profile_form': profile_form,
            'registered': registered
        }) 

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            return render(request, 'rango/login.html', {'error_message': "Please Provide correct username and password!"})
    else:
        return render(request, 'rango/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def restricted(request):
    return render(request, 'rango/restricted.html', {})

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
About Rango
{% endblock %}

{% block body_block %}
    <h1>About Page</h1>
    <span>{{visits}} total visit</span>
    <div>
        <p>This tutorial has been put together by {{my_name}}</p>
        <img src="{{ MEDIA_URL }}cat.jpg" />
    </div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% block title_block %}
Add Category
{% endblock %}

{% block body_block %}
    <h1>Add a Category</h1>
    <div>
        <form id="category_form" method="post" action="{% url 'rango:add_category'%}">
            {% csrf_token %} 
            {% for hidden in form.hidden_fields %} 
                {{ hidden }} 
            {% endfor %} 
            {% for field in form.visible_fields %}
                {{ field.errors }} 
                {{ field.help_text }} 
                {{ field }} 
            {% endfor %}
            <input type="submit" name="submit" value="Create Category" />
        </form>
    </div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Add a Page
{% endblock %}

{% block body_block %}
    <h1>Add a Page for <strong>{{ category.name }}</strong> Category</h1>
    <div>
        <form id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
            {% csrf_token %} 
            {% for hidden in form.hidden_fields %} 
                {{ hidden }} 
            {% endfor %} 
            {% for field in form.visible_fields %}
                <div>
                {{ field.errors }} 
                </div>
                <div>
                {{ field.help_text }} 
                {{ field }}
                </div> 
            {% endfor %}
            <input type="submit" name="submit" value="Add Page" />
        </form>
    </div>
{% endblock %}
    

templates/rango/base.html
<!DOCTYPE html> 
{% load staticfiles %}
{% load rango_template_tags %}
<html>

<head lang="en">
    <meta charset="UTF-8" />
    <title>
        Rango - 
        {% block title_block %}
            How to Tango with Django!
        {% endblock %}
    </title>
    <!-- CSS -->
    <link rel="stylesheet" href="{% static "css/base.css" %}" />
</head>

<body class="home">
    <div>
        <ul>
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'rango:about' %}">About</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                 <li><a href="{% url 'auth_password_change' %}">Change Password</a></li>
                <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                
            {% else %}
                <li><a href="{% url 'auth_login' %}">Sign In</a></li>
                <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
            {% endif %}
        </ul>
    </div>
    <hr />
    <div>
        {% block sidebar_block %}
            {% get_category_list category %}
        {% endblock %}
    </div>
    <div>
        {% block body_block %}
        {% endblock %}
    </div>
    <!-- JavaScript -->
    <script src="{% static "js/jquery.js" %}"></script>
</body>

</html>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
{{ category.name }}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
        <ul>
            {% for page in pages %}
            <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <strong>No pages currently in category.</strong> 
        {% endif %}
        {% if user.is_authenticated %}
        <a href="{% url 'rango:add_page' category.slug %}">Add a Page</a>
        {% endif %}
    {% else %} 
        The specified category does not exist! 
    {% endif %}
{% endblock %}

templates/rango/cats.html
<ul>
    {% if cats %} 
        {% for c in cats %}
            {% if c == act_cat %}
                <li>
                    <strong>
                        <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                    </strong>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                </li>
            {% endif %}
        {% endfor %} 
    {% else %}
    <li> <strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

templates/rango/index.html
{% extends 'rango/base.html' %}
{% block title_block %}
Homepage
{% endblock %}

{% block body_block %}
<h1>Rango says...</h1>
<div>
    {% if user.is_authenticated %}
    howdy {{ user.username }}!
    {% else %}
    hey there partner!
    {% endif %}
    <br/><br/>
    {% if user.is_authenticated %}
    <a href="{% url 'rango:add_category' %}">Add a New Category</a><br />
    {% endif %}
</div>

<h2>Most Liked Categories</h2>
<div>
    {% if categories %}
    <ul>
        {% for category in categories %}
        <li>
            <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <strong>There are no categories present.</strong> 
    {% endif %}
</div>

<h2>Most Viewed Pages</h2>
<div>
    {% if pages %}
    <ul>
        {% for page in pages %}
        <li>
            <a href="{{ page.url }}">{{ page.title }}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <strong>There are no categories present.</strong> 
    {% endif %}
</div>
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %} 
{% load staticfiles %} 
{% block title_block %} 
Login 
{% endblock %} 
{% block body_block %}
<h1>Login to Rango</h1>
{% if error_message %}
<p>{{ error_message }}</p>
{% endif %}
<form id="login_form" method="post" action="{% url 'rango:login' %}">
    {% csrf_token %} 
    Username: <input type="text" name="username" value="" size="50" />
    <br /> Password: <input type="password" name="password" value="" size="50" />
    <br />
    <input type="submit" value="submit" />
</form>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %} 
{% load staticfiles %} 
{% block title_block %} Register 
{% endblock %} 

{% block body_block%}
<h1>About Page</h1>
{% if registered %} Rango says: <strong>thank you for registering!</strong>
    <a href="{% url 'index' %}">Return to the homepage.</a><br /> 
{% else %} 
    Rango says: <strong>register here!</strong><br />
<form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- Display each form -->
    {{ user_form.as_p }} {{ profile_form.as_p }}
    <!-- Provide a button to click to submit the form. -->
    <input type="submit" name="submit" value="Register" />
</form>
{% endif %} 
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %} 
{% block title_block %} 
Restricted Page
{% endblock %} 
{% block body_block %}
<h1>Restricted Page</h1>
<p>Since you're logged in, you can see this text!</p>
{% endblock %}